"""
Combines the live agri signal and the speech-emotion classifier output
into a single applicant-level score.

HONESTY NOTE, load-bearing for the whole project:
The weighting logic below is a transparent, rule-based DEMO scoring
function that we designed for this hackathon prototype. It is NOT a
trained credit-risk model, has NOT been validated against real loan
outcomes, and the "emotion -> risk" link in particular is a proposed,
unproven hypothesis rather than an established underwriting signal.
Every response from this endpoint says so explicitly (`disclaimer`
field) so nothing here can be mistaken for a production decision.
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app import models
from app.database import get_db
from app.security.auth import get_current_user

router = APIRouter(prefix="/credit", tags=["credit"])

DISCLAIMER = (
    "SIMULATED DEMO OUTPUT. This score is generated by a transparent, "
    "hand-written rule set for a hackathon prototype. It has not been "
    "validated against real repayment data and must not be used for any "
    "real lending decision. In particular, the speech-emotion component "
    "reflects a detected emotion category only -- it is not a validated "
    "measure of honesty or repayment intent."
)

# Rule-based weights, fully disclosed -- this replaces the earlier "SHAP"
# framing, which implied a trained model's real feature importances.
EMOTION_RISK_WEIGHT = {
    "calm": -0.05, "neutral": 0.0, "happy": -0.03,
    "sad": 0.05, "angry": 0.08, "fearful": 0.06,
    "disgust": 0.04, "surprised": 0.02,
}


@router.post("/assess/{applicant_id}")
def assess(
    applicant_id: str,
    agri_data: dict,
    emotion_data: dict,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    applicant = db.query(models.Applicant).filter(models.Applicant.id == applicant_id).first()
    if not applicant:
        raise HTTPException(status_code=404, detail="Applicant not found.")

    base_risk = 0.30  # starting point, disclosed
    explanation = [{"factor": "base_risk", "contribution": base_risk, "note": "Fixed starting point for the demo."}]

    risk_flag = agri_data.get("risk_flag")
    agri_adjustment = {"drought_risk": 0.15, "flood_saturation_risk": 0.10, "normal": -0.05}.get(risk_flag, 0.0)
    explanation.append({
        "factor": "agri_soil_signal",
        "contribution": agri_adjustment,
        "note": f"Live Open-Meteo soil moisture risk flag: '{risk_flag}'.",
    })

    predicted_emotion = emotion_data.get("predicted_emotion")
    emotion_adjustment = EMOTION_RISK_WEIGHT.get(predicted_emotion, 0.0)
    emotion_mode = emotion_data.get("mode", "unknown")
    explanation.append({
        "factor": "speech_emotion_signal",
        "contribution": emotion_adjustment,
        "note": (f"Detected emotion '{predicted_emotion}' (classifier mode: {emotion_mode}). "
                 "Experimental signal -- see disclaimer."),
    })

    total_risk = max(0.01, min(0.99, base_risk + agri_adjustment + emotion_adjustment))

    if total_risk < 0.30:
        decision, ltv_cap = "APPROVED", "85%"
    elif total_risk < 0.50:
        decision, ltv_cap = "APPROVED_WITH_CONDITIONS", "70%"
    elif total_risk < 0.70:
        decision, ltv_cap = "MANUAL_REVIEW_REQUIRED", "50%"
    else:
        decision, ltv_cap = "DECLINED_PENDING_MANUAL_REVIEW", "0%"

    result = {
        "disclaimer": DISCLAIMER,
        "applicant_id": applicant_id,
        "total_simulated_risk": round(total_risk, 3),
        "decision": decision,
        "suggested_ltv_cap": ltv_cap,
        "explanation": explanation,
    }

    assessment = models.Assessment(
        applicant_id=applicant_id,
        agri_data=agri_data,
        emotion_data=emotion_data,
        combined_score=result,
    )
    db.add(assessment)
    db.commit()
    db.refresh(assessment)

    result["assessment_id"] = assessment.id
    return result
